name: httpstan

on: [push, pull_request]

jobs:
  tests:
    name: httpstan tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-24.04
            python-version: "3.13"
          - os: macos-14
            python-version: "3.11"
          - os: macos-15
            python-version: "3.12"
          - os: macos-15
            python-version: "3.13"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install "poetry~=2.2.1"

      - name: Build libraries used by Stan
        run: make -j2

      # export test dependencies from pyproject.toml, install them
      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
        run: |
          poetry export -f requirements.txt --without-hashes --with dev -o requirements.txt \
          && pip install -r requirements.txt

      - name: Check code
        run: scripts/check

      - name: Build and Install wheel
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
        run: |
          poetry build -v
          python -m pip install dist/*.whl

      - name: Run tests
        run: python -m pytest -s -v tests

      - name: Test PyStan compatibility
        run: |
          pip install --pre pystan
          python -c'import stan;assert stan.build("parameters {real y;} model {y ~ normal(0,1);}").sample()["y"] is not None'
