name: wheel - manylinux2014

on:
  push:
    tags:
      - '*'
jobs:
  wheel_manylinux:
    name: manylinux2014
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [cp37-cp37m, cp38-cp38]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          echo "::add-path::/opt/python/${{ matrix.python-version }}/bin/"
      - name: check C++ compiler and Python
        run: |
          which gcc
          gcc --version
          g++ --version
          python --version
          which python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir "poetry<2,>=1.0"
          python -m pip install --no-cache-dir "mypy-protobuf~=1.0"
      - name: Build libraries
        run: |
          make
      - name: Build wheel
        run: |
          python -m poetry build -v
      - name: Fix wheel
        env:
          PLAT: manylinux2014_x86_64
        run: |
          for whl in dist/*.whl; do
            auditwheel repair "${whl}" --plat "${PLAT}" -w "./dist"
            rm ${whl}
          done
          python -m pip install  --no-cache-dir dist/*.whl
      - name: Tests
        env:
          PYTEST_ARGS: "--forked"
        if: success()
        run: |
          # export test dependencies from pyproject.toml, install them
          python -m poetry export -f requirements.txt --dev -o requirements.txt && pip install -r requirements.txt
          mkdir testdir && cd testdir
          poetry run pytest -s -v --cov=httpstan --cov-fail-under=93 $PYTEST_ARGS ../tests
          cd ..
      - name: Upload to pypi
        if: success()
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python -m pip install --no-cache-dir twine
          twine upload --repository-url https://test.pypi.org/legacy/ -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} --skip-existing dist/*
