name: macOS

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  page_build:
    release:
      types:
        - created

jobs:
  tests:
    name: tests
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        compiler: [clang]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install gnu-findutils
        run: |
          brew install findutils
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "poetry<2,>=1.0"
          pip install "mypy-protobuf~=1.0"
      - name: Build dependencies
        env:
          CC: ${{ matrix.compiler }}
        run: |
          PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
          make
      - name: Install and run tests
        env:
          CC: ${{ matrix.compiler }}
        run: |
          poetry install -v && poetry run pytest -s -v --cov=httpstan --cov-fail-under=93 tests
          cat codecov.yml | curl --data-binary @- https://codecov.io/validate
          bash <(curl -s https://codecov.io/bash) -n="${name}"
